#!/bin/bash

spyOnContentFiles() {
    decompiledFolderBaseName=$(basename $1)
    reportOutputDir=$2
    contentFilePaths=$(find "$reportOutputDir/$decompiledFolderBaseName-decompiled" -name "*.md*" -o -name "*.txt*" -o -name "*.html*" -o -name "*.htm*" -o -name "*.css*" -o -name "*.js" | grep -Ea "assets" | sort -u)
    
    if [ -n "$contentFilePaths" ]; then
        echo ""
        
        mkdir -p $reportOutputDir/content_files
        
        echo ""
        for contentFilePath in $contentFilePaths ; do
            onlyFileName=$(basename $contentFilePath)
            
            echo "Found $onlyFileName file."
            
            targetPath=$reportOutputDir/content_files/file_$onlyFileName
            #echo "Copying $contentFilePath to $targetPath"
            cp $contentFilePath $targetPath
            
        done
    else
        echo "No .md, .txt, .html, .htm, .css or .js files found."
    fi
    
    
}