#!/bin/bash

decompileApp() {
    local file=$1
    local reportOutputDir=$2
    
    echo "Decompiling $file..."
    
    jadxPath=$(which jadx)
    
    echo "jadx path: $jadxPath"
    
    $jadxPath -d "$file-decompiled" $file
    
    if [ $? -eq 0 ]; then
        mv "$file-decompiled" $reportOutputDir
        
        echo "Decompiled $file successfully."
    else
        echo "Failed to decompile $file."
        exit 1
    fi
}
