#!/bin/bash

extractEmailsFromLibAppSoFile() {
    soFiles="$1/libapp"
    
    emails=$(grep -Eioa "[-0-9a-zA-Z.+_]+@[-0-9a-zA-Z.+_]+\.[a-zA-Z]{2,4}" -rh $soFiles | grep -Eiah "^[^_]" | sort -u)
    
    echo ""
    echo "emails:"
    echo $emails
    echo ""
    
    echo "$emails" > $reportOutputDir/emails.txt
}

extractUrlsFromLibAppSoFile() {
    soFiles="$1/libapp"
    
    uriFormattedCommand=$(grep -Eioa "\b\w+:\/\/[-A-Za-z0-9+&@#\/%?=~_|!:,.;]*[-A-Za-z0-9+&@#\/%=~_|]+" -rh $soFiles | sort -u)
    
    #   echo $("$uriFormattedCommand")
    
    httpAndHttpsUrls=$(echo "$uriFormattedCommand" | grep -Eia '^(http|https)' | sort -u)
    echo "HTTP and HTTPs Urls:"
    for url in $httpAndHttpsUrls ; do
        echo $url
    done
    echo ""
    
    ftpUrls=$(echo "$uriFormattedCommand" | grep -Eia '^(ftp)' | sort -u)
    echo "FTP Urls:"
    for url in $ftpUrls ; do
        echo $url
    done
    echo ""
    
    wsAndWssUrls=$(echo "$uriFormattedCommand" | grep -Eia '^(ws|wss)' | sort -u)
    echo "WS and WSS Urls:"
    for url in $wsAndWssUrls ; do
        echo $url
    done
    echo ""
    
    fileprotocolUrls=$(echo "$uriFormattedCommand" | grep -Eia '^(file)' | sort -u)
    echo "File protocol paths"
    for url in $fileprotocolUrls ; do
        echo $url
    done
    echo ""
    
    
    # other urls, exluding http, https, ftp, ws, wss
    otherUrls=$(echo "$uriFormattedCommand" | grep -Eia -v '^(http|https|ftp|ws|wss|file)' | sort -u)
    echo "Other URIs:"
    for url in $otherUrls ; do
        echo $url
    done
    echo ""
    
    echo "$uriFormattedCommand" > $reportOutputDir/urls.txt
}

extractPhoneNumbersFromLibAppSoFile() {
    soFiles="$1/libapp"
    
    phoneNumbers=$(grep -iaoP "\b(?:\+?[0-9()-.\s]*){7,}\b" -rh $soFiles | awk 'length($0) > 9' | sort -u)
    
    all=$(echo "$phoneNumbers")
    
    echo ""
    echo "Potential Phone numbers:"
    for phoneNumber in $all ; do
        echo $phoneNumber
    done
    echo ""
    
    echo "$phoneNumbers" > $reportOutputDir/phone_numbers.txt
}

extractApiEndpointsFromLibAppSoFile() {
    soFiles="$1/libapp"
    
    apiEndpoints=$(grep -Eioa "\/[a-zA-Z0-9_-]+\/?[a-zA-Z0-9_-]*" -rh $soFiles | awk 'length($0) > 3' | grep -vi ".dart" | sort -u)
    
    all=$(echo "$apiEndpoints")
    
    echo ""
    echo "Potential API endpoints:"
    for apiEndpoint in $all ; do
        echo $apiEndpoint
    done
    echo ""
    
    echo "$apiEndpoints" > $reportOutputDir/api_endpoints.txt
}

extractPackageNamesFromLibAppSoFile() {
    soFiles="$1/libapp"
    
    pathFromAppFlutterPackageName=$(grep -Eoa 'package:.*main.dart' -rh $soFiles | sort -u)
    
    appFlutterPackageName=$(echo "$pathFromAppFlutterPackageName" | awk -F'[:/]' '{print $2}' | sort -u)
    
    
    packageNames=$(grep -Eoa 'package:.*dart' -rh $soFiles | awk 'length($0) > 3' | grep -oP ':\K[^:/]+/' | grep -va "$appFlutterPackageName" | awk -F '/' '{print $1}'| sort -u)
    
    all=$(echo "$packageNames")
    
    echo ""
    echo "Potential FLutter packages:"
    for packageName in $all ; do
        echo "https://pub.dev/packages/$packageName"
    done
    echo ""
    
    echo "$packageNames" > $reportOutputDir/packages.txt
    
    ######################################################
    
    pathsOfFlutterAppPackageName=$(grep -Eoa "package:$appFlutterPackageName.*dart" -rh $soFiles | sort -u)
    
    echo ""
    
    echo "Paths of $appFlutterPackageName: (The app flutter package name)"
    for path in $pathsOfFlutterAppPackageName ; do
        echo $path
    done
    
    echo ""
    echo "$pathsOfFlutterAppPackageName" > $reportOutputDir/paths_of_flutter_app_package_name.txt
}



extractInfoFromLibAppSoFile() {
    
    libappSoFile=$1
    reportOutputDir=$2
    
    
    mkdir -p $reportOutputDir/libapp
    pwd
    echo "Copying $libappSoFile to $reportOutputDir/libapp/libapp.so"
    
    cp $libappSoFile "$reportOutputDir/libapp/libapp.so"
    echo "libapp.so copied to $reportOutputDir/libapp/libapp.so"
    
    
    extractEmailsFromLibAppSoFile $reportOutputDir
    extractUrlsFromLibAppSoFile $reportOutputDir
    extractPhoneNumbersFromLibAppSoFile $reportOutputDir
    extractApiEndpointsFromLibAppSoFile $reportOutputDir
    extractPackageNamesFromLibAppSoFile $reportOutputDir
    
}


