#!/bin/bash

spyOnLibAppSoFile() {
    reportOutputDir=$2
    onlyApkFileName=$(basename $1)
    
    fromLibAppSoFile=$(find  $2/$onlyApkFileName-decompiled -name "libapp.so")
    
    if [ $? -eq 0 ]; then
        echo ""
        echo "Found libapp.so files:"
        for libAppSoFile in $fromLibAppSoFile ; do
            echo $libAppSoFile
        done
        
        
        firstLibAppSoFile=$(echo $fromLibAppSoFile | cut -d ' ' -f 1)
        echo ""
        echo "Flutter Spy will use $firstLibAppSoFile to extract information."
        echo ""
        extractInfoFromLibAppSoFile $firstLibAppSoFile $reportOutputDir
        
    else
        echo "Failed to find libapp.so file, please make sure that the provided apk file is a flutter app."
        exit 1
    fi
    
}



startSpy() {
    
    reportOutputDir="report-$(date +%Y-%m-%d-%H-%M-%S)"
    mkdir -p $reportOutputDir
    
    decompileApp $1 $reportOutputDir
    spyOnLibAppSoFile $1 $reportOutputDir
    spyOnEnvFiles $1 $reportOutputDir
    spyOnAssetConfigFiles $1 $reportOutputDir
}
