#!/bin/bash

# 1.0.0

echo -e "\e[33mFlutter-spy is under active development, please check https://github.com/anasfik/flutter-spy/ for updates.\e[0m"
echo ""

providedFileName=$(pwd)/$1

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

source "$DIR/lib/utils"
source "$DIR/lib/spy"
source "$DIR/lib/decompile"
source "$DIR/lib/info_from_libapp"
source "$DIR/lib/env_files"
source "$DIR/lib/asset_config_files"
source "$DIR/lib/content_files"
source "$DIR/lib/visual_asset_files"

if noArgumentsProvided $@; then
    showRootCommandContent
    exit 0
else
    echo "File name provided: $providedFileName"
fi

echo $providedFileName
if doesFileExist $providedFileName; then
    echo ""
    echo "File $providedFileName exists."
else
    echo "File $providedFileName does not exist."
    exit 1
fi


if jadxExist $providedFileName; then
    echo ""
    echo "Jadx is installed."
else
    echo "Jadx is not found, Please install it."
    exit 1
fi



if isProvidedFileApk $providedFileName; then
    echo ""
    echo "File $providedFileName is an apk file."
else
    echo "File $providedFileName is not an apk file."
    exit 1
fi

startSpy $providedFileName