#!/bin/bash

echo -e "\e[33mFlutter-spy is under active development, please check https://github.com/anasfik/flutter-spy/ for updates.\e[0m"
echo ""

jadxPath="/home/gwhyyy/jadx-1.4.7/bin/jadx"

providedFileName=$(pwd)/$1

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

source "$DIR/lib/utils"
source "$DIR/lib/spy"
source "$DIR/lib/decompile"
source "$DIR/lib/extract_info_from_libapp"


if noArgumentsProvided $@; then
    echo "No arguments provided. Please provide a file name."
    exit 1
else
    echo "File name provided: $providedFileName"
fi

echo $providedFileName
if doesFileExist $providedFileName; then
    echo ""
    echo "File $providedFileName exists."
else
    echo "File $providedFileName does not exist."
    exit 1
fi


if jadxExist $providedFileName; then
    echo ""
    echo "Jadx is installed."
else
    echo "Jadx is not found, Please install it."
    exit 1
fi



if isProvidedFileApk $providedFileName; then
    echo ""
    echo "File $providedFileName is an apk file."
else
    echo "File $providedFileName is not an apk file."
    exit 1
fi

startSpy $providedFileName